### ISSUE TITLE
help check TN chapter 1 notes on cross correlation of spikes

### ISSUE THREAD

**Issue by zym1010** [leelabcnbc/machine-learning-notes#2]
@wenhao-z  can you help check out <https://github.com/leelabcnbc/book-notes/blob/master/books/TN/chapter_01.ipynb>, regarding my notes and code on pp. 28 of the book? I feel the book is wrong, but I'm not sure. I feel you are expert on this. thanks.

**Comment by wenhao-z** [comment]
I don't quite understand why you say the send term in your Eq. 4 is not well defined.
If you take an integral, the \rho(t) should be a series of Dirac delta function. If you discretize the integral into summation, the Dirac delta function should be also changed into Keronecker delta function. This is an implementation issue. But from theory, I think this equation is out of problem.

EDIT from Yimeng: Check <http://www.gatsby.ucl.ac.uk/~hehrmann/TN1/notes-spike-stats.pdf>. pp. 9. I feel it's not right...

**Comment by wenhao-z** [comment]
Also, a comment on your "pp.10 below Eq. (1.6)"
The trial averaged spike train can be obtained in experimental case, just repeat the stimulus for several times.

**Comment by wenhao-z** [comment]
Also, for "pp. 22 white noise stimuli"
I think white and Gaussian are two aspects of a stochastic process without overlapping on their definition. Gaussian just means the temporal process satisfying a Gaussian process, but not sure whether they are temporally correlated or independent. A Gaussian noise can be temporally correlated, like the OU process is a type of Gaussian process. White is stating that they temporal process is temporally independent.

**Comment by zym1010** [comment]
<https://github.com/leelabcnbc/book-notes/issues/2#issuecomment-324042839> fixed by <https://github.com/leelabcnbc/book-notes/commit/7a2df185cfbafb93276b797e3bc34dd02d75227c>

**Comment by zym1010** [comment]
I thought more about this spike train correlation issue. I think main difficulty is similar to taht in the definition of `\langle \rho(t) \rangle`. By naive definition of average, I should get a bunch of Dirac functions divided by `N`, where `N` is number of trails, and the density of these Dirac functions should be related to firing rate. This `\delta/N` thing doesn't seem good to me mathematically.

**Comment by zym1010** [comment]
@wenhao-z  I did simulation. check latest version of notes, such as <https://github.com/leelabcnbc/book-notes/blob/0d1df228fb08336d641033021ab8b05c290c7d50/books/TN/chapter_01.ipynb>.
